# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitecture: 'x64'
    jdkSourceOption: 'PreInstalled'
    
- task: Maven@3
  inputs:
    mavenVersionOption: 'Default'
    mavenPomFile: 'pom.xml'
    options: '$(MAVEN_OPTS)'
    goals: 'clean package -Pdist -Pindex'
    
- task: NexusIqPipelineTask@2
  inputs:
    nexusIqService: 'int-test.sonatype.app'
    applicationId: 'maria-test-app'
    stage: 'Build'
    scanTargets: '**/*.jar, **/*.zip'
    enableCallflow: true
    callflowNamespaces: 'org.sonatype.lifecycle.jenkins.examples.callflow'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'bomxray.log'
    targetPath: '**/bomxray.log'
