# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main  # or 'master' if that’s your default branch

pool:
  vmImage: ubuntu-22.04

variables:
  MAVEN_OPTS: "-Xmx3072m"

steps:
- script: |
    echo "Java version:"
    java -version
  displayName: 'Check Java version'

- task: Maven@4
  inputs:
    mavenVersionOption: 'Default'
    mavenPomFile: 'pom.xml'
    goals: 'clean package -Pdist -Pindex'

- task: NexusIqPipelineTask@2
  inputs:
    nexusIqService: 'int-test.sonatype.app'
    applicationId: 'maria-test-app'
    stage: 'Build'
    scanTargets: '**/*.jar, **/*.zip'
    enableCallflow: true 
    callflowNamespaces: 'org.sonatype.lifecycle.jenkins.examples.callflow'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'bomxray.log'
    targetPath: '**/bomxray.log'

