# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  mavenVersion: '3.9'
  javaVersion: '17'
  buildConfiguration: 'Release'

steps:
- task: UseJava@1
  inputs:
    versionSpec: '17'
    jdkArchitecture: 'x64'
 
- task: Maven@3
  inputs:
    mavenVersionOption: 'Default'
    mavenSetM2Home: true 
    options: '-B -V -e -U'
    goals: 'clean package -Pdist -Pindex'
    
- task: NexusIqPipelineTask@2
  inputs:
    nexusIqService: 'int-test.sonatype.app'
    applicationId: 'maria-test-app'
    stage: 'Build'
    scanTargets: '**/*.jar, **/*.zip'
    enableCallflow: true 
    callflowNamespaces: 'org.sonatype.lifecycle.jenkins.examples.callflow'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'bomxray.log'
    targetPath: '**/bomxray.log'
